### ISSUE TITLE
有关额外分类器 attr_clf_au 和 obj_clf_au 的疑问

### ISSUE THREAD

**Issue by bighuang624** [PRIS-CV/IVR#1]
抱歉由于感觉用英文无法全面表达我的疑问，我用中文提了这条 issue。用中文或者英文回复都 ok。
首先恭喜你们中了 ECCV 2022，并感谢你们第一时间将代码开源。我已经尝试了你们的代码，并发现你们的方法确实很有效。然而，我注意到除开 attr_clf 和 obj_clf，你们额外的初始化了两个分类器 attr_clf_au 和 obj_clf_au，这两个分类器特供于 $(a, \overline{o})$ 的 attr 特征和 $(\overline{a}, o)$ 的 obj 特征。我在论文中似乎没有发现有关这两个额外分类器的表述，并且在刚阅读论文时也认为是用 attr_clf 来处理 $(a, \overline{o})$ 的 attr 特征，用 obj_clf 来处理 $(\overline{a}, o)$ 的 obj 特征，因为论文中只有 $\theta_j$。你们可以解释一下单独为这些特征使用这两个额外分类器的原因吗？如果是我理解有误，或者论文的某个地方已经做过解释但是我没注意到，也麻烦你们指出。
再次感谢你们，希望能够获得回复！

**Comment by dongliangchang** [comment]
@TIan1874

**Comment by TIan1874** [comment]
Thanks for your attention to our work!

Taking $(a, o)$ and $(a, \overline{o})$ as examples, object is used as domain to train the attribute classifier. The gradients of attribute prediction results with respect to the attribute representations are calculated, and the mask obtained by comparing them is used to learn the object-domain invariant features. If use the same attribute classifier, the resulting gradients are also the same, and the purpose of seeking difference and invariance at the representation level can not be achieved. Therefore, an additional classifier is introduced as an auxiliary for learning domain-invariant features.
